theme = "themes/nightfox.json"

[keys.normal]
"u" = "Undo"
"q" = "Quit"
"s" = "Save"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Up" = "MoveUp"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"
"i" = "InsertMode"
"a" = "InsertAfter"
"Escape" = "NormalMode"
"x" = "DeleteUnderCursor"
"o" = "InsertLineAfter"
"S-O" = "InsertLineAbove"
"Enter" = "InsertLineAfter"
"dd" = "DeleteLine"
"d" = {"d" = "DeleteLine", "w" = "DeleteWord"}
"w" = "MoveWordRight"
"b" = "MoveWordLeft"
"S-E" = "MoveToEndOfLine"
"S-B" = "MoveToStartOfLine"

[keys.insert]
"Escape" = "NormalMode"
"Enter" = "InsertLineAfter"
