theme = "themes/nightfox.json"

[keys.normal]
"q" = "Quit"
"s" = "Save"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Up" = "MoveUp"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"
"i" = "InsertMode"
"Escape" = "NormalMode"
"x" = "DeleteUnderCursor"
"o" = "InsertLineAfter"
"S-O" = "InsertLineAbove"
"Enter" = "InsertLineAfter"
"dd" = "DeleteLine"
"d" = {"d" = "DeleteLine", "w" = "DeleteWord"}

[keys.insert]
"Escape" = "NormalMode"
"Enter" = "InsertLineAfter"
