theme = "themes/nightfox.json"

[keys.normal]
"q" = "Quit"
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Up" = "MoveUp"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"
"i" = "InsertMode"
"Escape" = "NormalMode"
"x" = "DeleteUnderCursor"

[keys.insert]
"Escape" = "NormalMode"
