# This is a sample configuration file for red.
#
# The configuration file is a TOML file. The configuration file is read from
# the following locations:
#
# 1. $XDG_CONFIG_HOME/red/config.toml
# 2. $HOME/.config/red/config.toml
# 

# Name of the VSCode theme to use. The theme file should be present in the
# themes directory: $XDG_CONFIG_HOME/red/themes or $HOME/.config/red/themes
theme = "mocha.json"

# The number of lines to scroll when using the mouse wheel
mouse_scroll_lines = 3
log_file = "/tmp/red.log"

[keys.normal]
"Down" = "MoveDown"
"Left" = "MoveLeft"
"Right" = "MoveRight"
"Up" = "MoveUp"
"k" = "MoveUp"
"j" = "MoveDown"
"h" = "MoveLeft"
"l" = "MoveRight"

[commands]
"quit" = "Quit"
